vim.cmd("colorscheme tokyonight")
vim.api.nvim_set_hl(0, "LineNrAbove", { fg = "cyan" })
vim.api.nvim_set_hl(0, "LineNr", { fg = "yellow" })
vim.api.nvim_set_hl(0, "LineNrBelow", { fg = "cyan" })
vim.api.nvim_set_hl(0, "NeoTreeNormal", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NeoTreeNormalNC", { bg = "NONE" })
